Fix various small issues

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -113,51 +113,51 @@ jobs:
     env:
       DJANGO_SETTINGS_MODULE: ptplot_site.settings.dev
     steps:
-    - name: Checkout
-      uses: actions/checkout@v7
-    - name: Setup Python
-      uses: actions/setup-python@v7
-      with:
-        python-version: ${{ env.PRIMARY_PYTHON_VERSION }}
-        cache: pip
-        cache-dependency-path: |
-          requirements.txt
-          requirements-dev.txt
-    - name: Print Python version
-      run: python -V
-    - name: Install requirements
-      run: |
-        pip install --upgrade pip wheel
-        pip install -r requirements.txt -r requirements-dev.txt
-    - name: Print Numba sysinfo
-      run: numba --sysinfo | tee numba-sysinfo.txt
-    - name: Create migrations
-      run: python manage.py makemigrations
-    - name: Migrate database
-      run: python manage.py migrate
-    - name: Check configuration
-      run: python manage.py check --fail-level WARNING
-    - name: Generate PTtools reference data
-      run: python3 -c "from pttools.bubble.fluid_reference import ref; ref()"
-    - name: Run tests with coverage
-      run: |
-        set -o pipefail
-        pytest --store-durations 2>&1 | tee test-output.txt
-    - name: Upload results
-      # The results are the most interesting when the tests have failed.
-      if: always()
-      uses: actions/upload-artifact@v7
-      with:
-        name: Test results
-        path: |
-          .test_durations
-          coverage.xml
-          coverage.json
-          htmlcov
-          test-output.txt
-        # The coverage reports are not created if the tests fail early.
-        if-no-files-found: warn
-    - name: Upload results to Codecov
-      uses: codecov/codecov-action@v7
-      with:
-        token: ${{ secrets.CODECOV_TOKEN }}
+      - name: Checkout
+        uses: actions/checkout@v7
+      - name: Setup Python
+        uses: actions/setup-python@v7
+        with:
+          python-version: ${{ env.PRIMARY_PYTHON_VERSION }}
+          cache: pip
+          cache-dependency-path: |
+            requirements.txt
+            requirements-dev.txt
+      - name: Print Python version
+        run: python -V
+      - name: Install requirements
+        run: |
+          pip install --upgrade pip wheel
+          pip install -r requirements.txt -r requirements-dev.txt
+      - name: Print Numba sysinfo
+        run: numba --sysinfo | tee numba-sysinfo.txt
+      - name: Create migrations
+        run: python manage.py makemigrations
+      - name: Migrate database
+        run: python manage.py migrate
+      - name: Check configuration
+        run: python manage.py check --fail-level WARNING
+      - name: Generate PTtools reference data
+        run: python3 -c "from pttools.bubble.fluid_reference import ref; ref()"
+      - name: Run tests with coverage
+        run: |
+          set -o pipefail
+          pytest --store-durations 2>&1 | tee test-output.txt
+      - name: Upload results
+        # The results are the most interesting when the tests have failed.
+        if: always()
+        uses: actions/upload-artifact@v7
+        with:
+          name: Test results
+          path: |
+            .test_durations
+            coverage.xml
+            coverage.json
+            htmlcov
+            test-output.txt
+          # The coverage reports are not created if the tests fail early.
+          if-no-files-found: warn
+      - name: Upload results to Codecov
+        uses: codecov/codecov-action@v7
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
